version: "3.8"

services:
  # Master
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: laravel_db
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=laravel_db
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --log-slave-updates=ON
      --read-only=0
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./master/init:/docker-entrypoint-initdb.d
    networks:
      - mysql-network

  # Slave 1
  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: laravel_db
    command: >
      --server-id=2
      --relay-log=relay-log-slave-1
      --read-only=1
      --gtid-mode=ON
      --enforce-gtid-consistency
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --log-slave-updates
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-slave-1-data:/var/lib/mysql
    networks:
      - mysql-network
    depends_on:
      - mysql-master

  # Slave 2
  mysql-slave-2:
    image: mysql:8.0
    container_name: mysql-slave-2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: laravel_db
    command: >
      --server-id=3
      --relay-log=relay-log-slave-2
      --read-only=1
      --gtid-mode=ON
      --enforce-gtid-consistency
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --log-slave-updates
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - mysql-slave-2-data:/var/lib/mysql
    networks:
      - mysql-network
    depends_on:
      - mysql-master

volumes:
  mysql-master-data:
  mysql-slave-1-data:
  mysql-slave-2-data:

networks:
  mysql-network:
    driver: bridge
